sudo: false
language: node_js
node_js:
  - "8"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
  directories:
    - "node_modules"
deploy:
  provider: script
  script: yarn deploy-storybook -- --ci --host-token-env-variable=GITHUB_TOKEN
  skip_cleanup: true
  on:
    branch: master