sudo: false
language: node_js
node_js:
  - "7"
cache:
  yarn: true
  directories:
    - "node_modules"
deploy:
  provider: script
  script: npm run deploy-storybook-ci
  skip_cleanup: true
  on:
    branch: master